# About this notebook
- [Luke](https://arxiv.org/pdf/2010.01057v1.pdf)-base starter notebook
- [Inference notebook](https://www.kaggle.com/yasufuminakama/jigsaw4-luke-base-starter-sub)
- Approach References
    - https://www.kaggle.com/c/jigsaw-toxic-severity-rating/discussion/286471
    - https://www.kaggle.com/debarshichanda/pytorch-w-b-jigsaw-starter
    - https://www.kaggle.com/debarshichanda/0-816-jigsaw-inference
    - Thanks for sharing @debarshichanda

# Directory settings

In [1]:
# ====================================================
# Directory settings
# ====================================================
import os

OUTPUT_DIR = './'
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

# CFG

In [2]:
# ====================================================
# CFG
# ====================================================
class CFG:
    competition='Jigsaw4'
    _wandb_kernel='nakama'
    debug=False
    apex=True
    print_freq=50
    num_workers=4
    model="studio-ousia/luke-base"
    scheduler='cosine' # ['linear', 'cosine']
    batch_scheduler=True
    num_cycles=0.5
    num_warmup_steps=0
    epochs=3
    encoder_lr=1e-5
    decoder_lr=1e-5
    min_lr=1e-6
    eps=1e-6
    betas=(0.9, 0.999)
    batch_size=64
    fc_dropout=0.
    text="text"
    target="target"
    target_size=1
    head=32
    tail=32
    max_len=head+tail
    weight_decay=0.01
    gradient_accumulation_steps=1
    max_grad_norm=1000
    margin=0.5
    seed=42
    n_fold=5
    trn_fold=[0, 1, 2, 3, 4]
    train=True

In [3]:
# ====================================================
# wandb
# ====================================================
import wandb

try:
    from kaggle_secrets import UserSecretsClient
    user_secrets = UserSecretsClient()
    secret_value_0 = user_secrets.get_secret("wandb_api")
    wandb.login(key=secret_value_0)
    anony = None
except:
    anony = "must"
    print('If you want to use your W&B account, go to Add-ons -> Secrets and provide your W&B access token. Use the Label name as wandb_api. \nGet your W&B access token from here: https://wandb.ai/authorize')

    
def class2dict(f):
    return dict((name, getattr(f, name)) for name in dir(f) if not name.startswith('__'))

run = wandb.init(project='Jigsaw4-Public', 
                 name=CFG.model,
                 config=class2dict(CFG),
                 group=CFG.model,
                 job_type="train",
                 anonymous=anony)

wandb: W&B API key is configured (use `wandb login --relogin` to force relogin)
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publically.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: yasufumi-nakama (use `wandb login --relogin` to force relogin)
wandb: wandb version 0.12.6 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade

# Library

In [4]:
# ====================================================
# Library
# ====================================================
import os
import gc
import re
import sys
import json
import time
import math
import string
import pickle
import random
import joblib
import itertools
import warnings
warnings.filterwarnings("ignore")

import scipy as sp
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
from tqdm.auto import tqdm
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold, GroupKFold, KFold

import torch
import torch.nn as nn
from torch.nn import Parameter
import torch.nn.functional as F
from torch.optim import Adam, SGD, AdamW
from torch.utils.data import DataLoader, Dataset

os.system('pip uninstall -q transformers -y')
os.system('pip uninstall -q tokenizers -y')
os.system('pip uninstall -q huggingface_hub -y')

os.system('mkdir -p /tmp/pip/cache-tokenizers/')
os.system('cp ../input/tokenizers-0103/tokenizers-0.10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl /tmp/pip/cache-tokenizers/')
os.system('pip install -q --no-index --find-links /tmp/pip/cache-tokenizers/ tokenizers')

os.system('mkdir -p /tmp/pip/cache-huggingface-hub/')
os.system('cp ../input/huggingface-hub-008/huggingface_hub-0.0.8-py3-none-any.whl /tmp/pip/cache-huggingface-hub/')
os.system('pip install -q --no-index --find-links /tmp/pip/cache-huggingface-hub/ huggingface_hub')

os.system('mkdir -p /tmp/pip/cache-transformers/')
os.system('cp ../input/transformers-470/transformers-4.7.0-py3-none-any.whl /tmp/pip/cache-transformers/')
os.system('pip install -q --no-index --find-links /tmp/pip/cache-transformers/ transformers')

import tokenizers
import transformers
print(f"tokenizers.__version__: {tokenizers.__version__}")
print(f"transformers.__version__: {transformers.__version__}")
from transformers import LukeTokenizer, LukeModel, LukeConfig
from transformers import get_linear_schedule_with_warmup, get_cosine_schedule_with_warmup

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

CondaEnvException: Unable to determine environment

Please re-run this command with one of the following options:

* Provide an environment name via --name or -n
* Re-run this command inside an activated conda environment.

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
allennlp 2.7.0 requires transformers<4.10,>=4.1, which is not installed.
datasets 1.14.0 requires huggingface-hub<0.1.0,>=0.0.19, but you have huggingface-hub 0.0.8 which is incompatible.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

tokenizers.__version__: 0.10.3
transformers.__version__: 4.7.0

# Utils

In [5]:
# ====================================================
# Utils
# ====================================================
def get_score(df):
    score = len(df[df['less_toxic_pred'] < df['more_toxic_pred']]) / len(df)
    return score


def get_logger(filename=OUTPUT_DIR+'train'):
    from logging import getLogger, INFO, StreamHandler, FileHandler, Formatter
    logger = getLogger(__name__)
    logger.setLevel(INFO)
    handler1 = StreamHandler()
    handler1.setFormatter(Formatter("%(message)s"))
    handler2 = FileHandler(filename=f"{filename}.log")
    handler2.setFormatter(Formatter("%(message)s"))
    logger.addHandler(handler1)
    logger.addHandler(handler2)
    return logger

LOGGER = get_logger()

def seed_everything(seed=42):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    
seed_everything(seed=42)

# Data Loading

In [6]:
# ====================================================
# Data Loading
# ====================================================
train = pd.read_csv('../input/jigsaw-toxic-severity-rating/validation_data.csv')
if CFG.debug:
    train = train.sample(n=100, random_state=CFG.seed).reset_index(drop=True)
test = pd.read_csv('../input/jigsaw-toxic-severity-rating/comments_to_score.csv')
submission = pd.read_csv('../input/jigsaw-toxic-severity-rating/sample_submission.csv')
print(train.shape)
print(test.shape, submission.shape)
display(train.head())
display(test.head())
display(submission.head())

(30108, 3)
(7537, 2) (7537, 2)

   worker                                         less_toxic                                         more_toxic
0     313            This article sucks \n\nwoo woo wooooooo  WHAT!!!!!!!!?!?!!?!?!!?!?!?!?!!!!!!!!!!!!!!!!!...
1     188  "And yes, people should recognize that but the...   Daphne Guinness \n\nTop of the mornin' my fav...
2      82   Western Media?\n\nYup, because every crime in...  "Atom you don't believe actual photos of mastu...
3     347  And you removed it! You numbskull! I don't car...  You seem to have sand in your vagina.\n\nMight...
4     539   smelly vagina \n\nBluerasberry why don't you ...           hey \n\nway to support nazis, you racist

   comment_id                                               text
0      114890  "\n \n\nGjalexei, you asked about whether ther...
1      732895  Looks like be have an abuser , can you please ...
2     1139051  I confess to having complete (and apparently b...
3     1434512  "\n\nFreud's ideas are certainly much discusse...
4     2084821  It is not just you. This is a laundry list of ...

   comment_id  score
0      114890    0.5
1      732895    0.5
2     1139051    0.5
3     1434512    0.5
4     2084821    0.5

# CV split

In [7]:
# ====================================================
# CV split
# ====================================================
Fold = GroupKFold(n_splits=CFG.n_fold)
for n, (trn_index, val_index) in enumerate(Fold.split(train, train, train['worker'])):
    train.loc[val_index, 'fold'] = int(n)
train['fold'] = train['fold'].astype(int)
display(train.groupby('fold').size())

fold
0    6022
1    6022
2    6022
3    6021
4    6021
dtype: int64

# tokenizer

In [8]:
# ====================================================
# tokenizer
# ====================================================
tokenizer = LukeTokenizer.from_pretrained(CFG.model, lowercase=True)
tokenizer.save_pretrained(OUTPUT_DIR+'tokenizer/')
CFG.tokenizer = tokenizer

Downloading:   0%|          | 0.00/899k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/15.3M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/33.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.00k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.04k [00:00<?, ?B/s]

# Dataset

In [9]:
# ====================================================
# Dataset
# ====================================================
def prepare_input(text, cfg):
    if cfg.tail == 0:
        inputs = cfg.tokenizer.encode_plus(text, 
                                           return_tensors=None, 
                                           add_special_tokens=True, 
                                           max_length=cfg.max_len,
                                           pad_to_max_length=True,
                                           truncation=True)
        for k, v in inputs.items():
            inputs[k] = torch.tensor(v, dtype=torch.long)
    else:
        inputs = cfg.tokenizer.encode_plus(text,
                                           return_tensors=None, 
                                           add_special_tokens=True, 
                                           truncation=True)
        for k, v in inputs.items():
            v_length = len(v)
            if v_length > cfg.max_len:
                v = np.hstack([v[:cfg.head], v[-cfg.tail:]])
            if k == 'input_ids':
                new_v = np.ones(cfg.max_len) * cfg.tokenizer.pad_token_id
            else:
                new_v = np.zeros(cfg.max_len)
            new_v[:v_length] = v 
            inputs[k] = torch.tensor(new_v, dtype=torch.long)
    return inputs


class TrainDataset(Dataset):
    def __init__(self, cfg, df):
        self.cfg = cfg
        self.less_toxic = df['less_toxic'].fillna("none").values
        self.more_toxic = df['more_toxic'].fillna("none").values

    def __len__(self):
        return len(self.less_toxic)

    def __getitem__(self, item):
        less_toxic_inputs = prepare_input(str(self.less_toxic[item]), self.cfg)
        more_toxic_inputs = prepare_input(str(self.more_toxic[item]), self.cfg)
        label = torch.tensor(1, dtype=torch.float)
        return less_toxic_inputs, more_toxic_inputs, label


class TestDataset(Dataset):
    def __init__(self, cfg, df):
        self.cfg = cfg
        self.text = df[cfg.text].fillna("none").values

    def __len__(self):
        return len(self.text)

    def __getitem__(self, item):
        text = str(self.text[item])
        inputs = prepare_input(text, self.cfg)
        return inputs

# Model

In [10]:
# ====================================================
# Model
# ====================================================
class CustomModel(nn.Module):
    def __init__(self, cfg, config_path=None, pretrained=False):
        super().__init__()
        self.cfg = cfg
        if config_path is None:
            self.config = LukeConfig.from_pretrained(cfg.model, output_hidden_states=True)
        else:
            self.config = torch.load(config_path)
        if pretrained:
            self.model = LukeModel.from_pretrained(cfg.model, config=self.config)
        else:
            self.model = LukeModel(self.config)
        self.fc_dropout = nn.Dropout(cfg.fc_dropout)
        self.fc = nn.Linear(self.config.hidden_size, cfg.target_size)
        
    def feature(self, inputs):
        outputs = self.model(**inputs)
        last_hidden_states = outputs[0]
        feature = torch.mean(last_hidden_states, 1)
        return feature

    def forward(self, inputs):
        feature = self.feature(inputs)
        output = self.fc(self.fc_dropout(feature))
        return output

# Helpler functions

In [11]:
# ====================================================
# Helper functions
# ====================================================
class AverageMeter(object):
    """Computes and stores the average and current value"""
    def __init__(self):
        self.reset()

    def reset(self):
        self.val = 0
        self.avg = 0
        self.sum = 0
        self.count = 0

    def update(self, val, n=1):
        self.val = val
        self.sum += val * n
        self.count += n
        self.avg = self.sum / self.count


def asMinutes(s):
    m = math.floor(s / 60)
    s -= m * 60
    return '%dm %ds' % (m, s)


def timeSince(since, percent):
    now = time.time()
    s = now - since
    es = s / (percent)
    rs = es - s
    return '%s (remain %s)' % (asMinutes(s), asMinutes(rs))


def train_fn(fold, train_loader, model, criterion, optimizer, epoch, scheduler, device):
    model.train()
    scaler = torch.cuda.amp.GradScaler(enabled=CFG.apex)
    losses = AverageMeter()
    start = end = time.time()
    global_step = 0
    for step, (less_toxic_inputs, more_toxic_inputs, labels) in enumerate(train_loader):
        for k, v in less_toxic_inputs.items():
            less_toxic_inputs[k] = v.to(device)
        for k, v in more_toxic_inputs.items():
            more_toxic_inputs[k] = v.to(device)
        labels = labels.to(device)
        batch_size = labels.size(0)
        with torch.cuda.amp.autocast(enabled=CFG.apex):
            less_toxic_y_preds = model(less_toxic_inputs)
            more_toxic_y_preds = model(more_toxic_inputs)
            loss = criterion(more_toxic_y_preds, less_toxic_y_preds, labels)
        losses.update(loss.item(), batch_size)
        if CFG.gradient_accumulation_steps > 1:
            loss = loss / CFG.gradient_accumulation_steps
        scaler.scale(loss).backward()
        grad_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), CFG.max_grad_norm)
        if (step + 1) % CFG.gradient_accumulation_steps == 0:
            scaler.step(optimizer)
            scaler.update()
            optimizer.zero_grad()
            global_step += 1
            if CFG.batch_scheduler:
                scheduler.step()
        end = time.time()
        if step % CFG.print_freq == 0 or step == (len(train_loader)-1):
            print('Epoch: [{0}][{1}/{2}] '
                  'Elapsed {remain:s} '
                  'Loss: {loss.val:.4f}({loss.avg:.4f}) '
                  'Grad: {grad_norm:.4f}  '
                  'LR: {lr:.8f}  '
                  .format(epoch+1, step, len(train_loader), 
                          remain=timeSince(start, float(step+1)/len(train_loader)),
                          loss=losses,
                          grad_norm=grad_norm,
                          lr=scheduler.get_lr()[0]))
        wandb.log({f"[fold{fold}] loss": losses.val,
                   f"[fold{fold}] lr": scheduler.get_lr()[0]})
    return losses.avg


def inference_fn(test_loader, model, device):
    preds = []
    model.eval()
    model.to(device)
    tk0 = tqdm(test_loader, total=len(test_loader))
    for inputs in tk0:
        for k, v in inputs.items():
            inputs[k] = v.to(device)
        with torch.no_grad():
            y_preds = model(inputs)
        preds.append(y_preds.sigmoid().to('cpu').numpy())
    predictions = np.concatenate(preds)
    return predictions

In [12]:
# ====================================================
# train loop
# ====================================================
def train_loop(folds, fold):
    
    LOGGER.info(f"========== fold: {fold} training ==========")

    # ====================================================
    # loader
    # ====================================================
    
    trn_idx = folds[folds['fold'] != fold].index
    val_idx = folds[folds['fold'] == fold].index
    
    train_folds = folds.loc[trn_idx].reset_index(drop=True)
    validation = folds.loc[val_idx].reset_index(drop=True)
    
    valid_folds = sorted(set(validation['less_toxic'].unique()) | set(validation['more_toxic'].unique()))
    valid_folds = pd.DataFrame({'text': valid_folds}).reset_index()
    
    train_dataset = TrainDataset(CFG, train_folds)
    valid_dataset = TestDataset(CFG, valid_folds)

    train_loader = DataLoader(train_dataset,
                              batch_size=CFG.batch_size,
                              shuffle=True,
                              num_workers=CFG.num_workers, pin_memory=True, drop_last=True)
    valid_loader = DataLoader(valid_dataset,
                              batch_size=CFG.batch_size,
                              shuffle=False,
                              num_workers=CFG.num_workers, pin_memory=True, drop_last=False)

    # ====================================================
    # model & optimizer
    # ====================================================
    model = CustomModel(CFG, config_path=None, pretrained=True)
    torch.save(model.config, OUTPUT_DIR+'config.pth')
    model.to(device)
    
    def get_optimizer_params(model, encoder_lr, decoder_lr, weight_decay=0.0):
        param_optimizer = list(model.named_parameters())
        no_decay = ["bias", "LayerNorm.bias", "LayerNorm.weight"]
        optimizer_parameters = [
            {'params': [p for n, p in model.model.named_parameters() if not any(nd in n for nd in no_decay)],
             'lr': encoder_lr, 'weight_decay': weight_decay},
            {'params': [p for n, p in model.model.named_parameters() if any(nd in n for nd in no_decay)],
             'lr': encoder_lr, 'weight_decay': 0.0},
            {'params': [p for n, p in model.named_parameters() if "model" not in n],
             'lr': decoder_lr, 'weight_decay': 0.0}
        ]
        return optimizer_parameters

    optimizer_parameters = get_optimizer_params(model,
                                                encoder_lr=CFG.encoder_lr, 
                                                decoder_lr=CFG.decoder_lr,
                                                weight_decay=CFG.weight_decay)
    optimizer = AdamW(optimizer_parameters, lr=CFG.encoder_lr, eps=CFG.eps, betas=CFG.betas)
    
    # ====================================================
    # scheduler
    # ====================================================
    def get_scheduler(cfg, optimizer, num_train_steps):
        if cfg.scheduler=='linear':
            scheduler = get_linear_schedule_with_warmup(
                optimizer, num_warmup_steps=cfg.num_warmup_steps, num_training_steps=num_train_steps
            )
        elif cfg.scheduler=='cosine':
            scheduler = get_cosine_schedule_with_warmup(
                optimizer, num_warmup_steps=cfg.num_warmup_steps, num_training_steps=num_train_steps, num_cycles=cfg.num_cycles
            )
        return scheduler
    
    num_train_steps = int(len(train_folds) / CFG.batch_size * CFG.epochs)
    scheduler = get_scheduler(CFG, optimizer, num_train_steps)

    # ====================================================
    # loop
    # ====================================================
    criterion = nn.MarginRankingLoss(margin=CFG.margin)
    
    best_score = 0.

    for epoch in range(CFG.epochs):

        start_time = time.time()

        # train
        avg_loss = train_fn(fold, train_loader, model, criterion, optimizer, epoch, scheduler, device)

        # eval
        preds = inference_fn(valid_loader, model, device)
        
        # scoring
        valid_folds['pred'] = preds
        if 'less_toxic_pred' in validation.columns:
            validation = validation.drop(columns='less_toxic_pred')
        if 'more_toxic_pred' in validation.columns:
            validation = validation.drop(columns='more_toxic_pred')
        rename_cols = {CFG.text: 'less_toxic', 'pred': 'less_toxic_pred'}
        validation = validation.merge(valid_folds[[CFG.text, 'pred']].rename(columns=rename_cols), 
                                      on='less_toxic', how='left')
        rename_cols = {CFG.text: 'more_toxic', 'pred': 'more_toxic_pred'}
        validation = validation.merge(valid_folds[[CFG.text, 'pred']].rename(columns=rename_cols), 
                                      on='more_toxic', how='left')
        score = get_score(validation)

        elapsed = time.time() - start_time

        LOGGER.info(f'Epoch {epoch+1} - avg_train_loss: {avg_loss:.4f}  time: {elapsed:.0f}s')
        LOGGER.info(f'Epoch {epoch+1} - Score: {score:.4f}')
        wandb.log({f"[fold{fold}] epoch": epoch+1, 
                   f"[fold{fold}] avg_train_loss": avg_loss, 
                   f"[fold{fold}] score": score})
        
        if score > best_score:
            best_score = score
            LOGGER.info(f'Epoch {epoch+1} - Save Best Score: {score:.4f} Model')
            torch.save({'model': model.state_dict(),
                        'preds': preds},
                        OUTPUT_DIR+f"{CFG.model.replace('/', '-')}_fold{fold}_best.pth")

    preds = torch.load(OUTPUT_DIR+f"{CFG.model.replace('/', '-')}_fold{fold}_best.pth", 
                       map_location=torch.device('cpu'))['preds']
    valid_folds['pred'] = preds
    if 'less_toxic_pred' in validation.columns:
        validation = validation.drop(columns='less_toxic_pred')
    if 'more_toxic_pred' in validation.columns:
        validation = validation.drop(columns='more_toxic_pred')
    rename_cols = {CFG.text: 'less_toxic', 'pred': 'less_toxic_pred'}
    validation = validation.merge(valid_folds[[CFG.text, 'pred']].rename(columns=rename_cols), 
                                  on='less_toxic', how='left')
    rename_cols = {CFG.text: 'more_toxic', 'pred': 'more_toxic_pred'}
    validation = validation.merge(valid_folds[[CFG.text, 'pred']].rename(columns=rename_cols), 
                                  on='more_toxic', how='left')

    torch.cuda.empty_cache()
    gc.collect()
    
    return validation

In [13]:
if __name__ == '__main__':
    
    def get_result(oof_df):
        score = get_score(oof_df)
        LOGGER.info(f'Score: {score:<.4f}')
    
    if CFG.train:
        # train 
        oof_df = pd.DataFrame()
        for fold in range(CFG.n_fold):
            if fold in CFG.trn_fold:
                _oof_df = train_loop(train, fold)
                oof_df = pd.concat([oof_df, _oof_df])
                LOGGER.info(f"========== fold: {fold} result ==========")
                get_result(_oof_df)
        oof_df = oof_df.reset_index(drop=True)
        # CV result
        LOGGER.info(f"========== CV ==========")
        get_result(oof_df)
        # save result
        oof_df.to_csv(OUTPUT_DIR+'oof_df.csv', index=False)
    
    wandb.finish()

========== fold: 0 training ==========

Downloading:   0%|          | 0.00/761 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.10G [00:00<?, ?B/s]

Some weights of the model checkpoint at studio-ousia/luke-base were not used when initializing LukeModel: ['embeddings.position_ids']
- This IS expected if you are initializing LukeModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LukeModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Epoch: [1][0/376] Elapsed 0m 3s (remain 20m 22s) Loss: 0.5035(0.5035) Grad: nan  LR: 0.00001000
Epoch: [1][50/376] Elapsed 0m 42s (remain 4m 28s) Loss: 0.4706(0.4106) Grad: 14139.0576  LR: 0.00000995
Epoch: [1][100/376] Elapsed 1m 20s (remain 3m 39s) Loss: 0.3246(0.3831) Grad: 13338.0635  LR: 0.00000980
Epoch: [1][150/376] Elapsed 1m 59s (remain 2m 58s) Loss: 0.3886(0.3721) Grad: 12700.3438  LR: 0.00000957
Epoch: [1][200/376] Elapsed 2m 38s (remain 2m 17s) Loss: 0.4029(0.3630) Grad: 12123.5859  LR: 0.00000924
Epoch: [1][250/376] Elapsed 3m 16s (remain 1m 38s) Loss: 0.3086(0.3594) Grad: 10969.6699  LR: 0.00000883
Epoch: [1][300/376] Elapsed 3m 55s (remain 0m 58s) Loss: 0.3089(0.3572) Grad: 11730.8857  LR: 0.00000835
Epoch: [1][350/376] Elapsed 4m 34s (remain 0m 19s) Loss: 0.3467(0.3558) Grad: 11160.4951  LR: 0.00000780
Epoch: [1][375/376] Elapsed 4m 53s (remain 0m 0s) Loss: 0.2918(0.3548) Grad: 11488.7607  LR: 0.00000750

  0%|          | 0/131 [00:00<?, ?it/s]

Epoch 1 - avg_train_loss: 0.3548  time: 312s
Epoch 1 - Score: 0.6979
Epoch 1 - Save Best Score: 0.6979 Model

Epoch: [2][0/376] Elapsed 0m 1s (remain 11m 40s) Loss: 0.3316(0.3316) Grad: nan  LR: 0.00000749
Epoch: [2][50/376] Elapsed 0m 40s (remain 4m 18s) Loss: 0.3987(0.3252) Grad: 12122.2598  LR: 0.00000687
Epoch: [2][100/376] Elapsed 1m 19s (remain 3m 35s) Loss: 0.2627(0.3227) Grad: 11553.2109  LR: 0.00000621
Epoch: [2][150/376] Elapsed 1m 57s (remain 2m 55s) Loss: 0.2920(0.3227) Grad: 10007.8516  LR: 0.00000552
Epoch: [2][200/376] Elapsed 2m 36s (remain 2m 16s) Loss: 0.3527(0.3208) Grad: 12691.4463  LR: 0.00000483
Epoch: [2][250/376] Elapsed 3m 15s (remain 1m 37s) Loss: 0.3097(0.3193) Grad: 13068.2734  LR: 0.00000413
Epoch: [2][300/376] Elapsed 3m 54s (remain 0m 58s) Loss: 0.3224(0.3193) Grad: 13120.8008  LR: 0.00000346
Epoch: [2][350/376] Elapsed 4m 32s (remain 0m 19s) Loss: 0.3023(0.3199) Grad: 11559.1816  LR: 0.00000282
Epoch: [2][375/376] Elapsed 4m 52s (remain 0m 0s) Loss: 0.3126(0.3197) Grad: 12815.3936  LR: 0.00000251

  0%|          | 0/131 [00:00<?, ?it/s]

Epoch 2 - avg_train_loss: 0.3197  time: 310s
Epoch 2 - Score: 0.7006
Epoch 2 - Save Best Score: 0.7006 Model
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
Exception ignored in:   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
<function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
      File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
self._shutdown_workers()
if w.is_alive():  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers

      File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
if w.is_alive():
assert self._parent_pid == os.getpid(), 'can only test a child process'

Epoch: [3][0/376] Elapsed 0m 1s (remain 10m 40s) Loss: 0.2601(0.2601) Grad: nan  LR: 0.00000250

  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive

    AssertionErrorassert self._parent_pid == os.getpid(), 'can only test a child process':
can only test a child processAssertionError
: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

Epoch: [3][50/376] Elapsed 0m 40s (remain 4m 17s) Loss: 0.2959(0.3018) Grad: 12868.1904  LR: 0.00000192
Epoch: [3][100/376] Elapsed 1m 18s (remain 3m 34s) Loss: 0.3195(0.3030) Grad: 12382.5430  LR: 0.00000140
Epoch: [3][150/376] Elapsed 1m 57s (remain 2m 55s) Loss: 0.2957(0.3023) Grad: 13282.9854  LR: 0.00000096
Epoch: [3][200/376] Elapsed 2m 36s (remain 2m 16s) Loss: 0.3640(0.3050) Grad: 13430.4941  LR: 0.00000059
Epoch: [3][250/376] Elapsed 3m 14s (remain 1m 37s) Loss: 0.3154(0.3058) Grad: 11946.8662  LR: 0.00000030
Epoch: [3][300/376] Elapsed 3m 53s (remain 0m 58s) Loss: 0.3302(0.3057) Grad: 14908.8350  LR: 0.00000011
Epoch: [3][350/376] Elapsed 4m 32s (remain 0m 19s) Loss: 0.3025(0.3043) Grad: 16081.8984  LR: 0.00000001
Epoch: [3][375/376] Elapsed 4m 51s (remain 0m 0s) Loss: 0.3344(0.3040) Grad: 13330.8135  LR: 0.00000000

  0%|          | 0/131 [00:00<?, ?it/s]

Epoch 3 - avg_train_loss: 0.3040  time: 310s
Epoch 3 - Score: 0.7029
Epoch 3 - Save Best Score: 0.7029 Model
========== fold: 0 result ==========
Score: 0.7029
========== fold: 1 training ==========
Some weights of the model checkpoint at studio-ousia/luke-base were not used when initializing LukeModel: ['embeddings.position_ids']
- This IS expected if you are initializing LukeModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LukeModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Epoch: [1][0/376] Elapsed 0m 1s (remain 11m 9s) Loss: 0.5052(0.5052) Grad: nan  LR: 0.00001000
Epoch: [1][50/376] Elapsed 0m 40s (remain 4m 17s) Loss: 0.3606(0.4154) Grad: 17261.8516  LR: 0.00000995
Epoch: [1][100/376] Elapsed 1m 19s (remain 3m 35s) Loss: 0.4566(0.3914) Grad: 13318.7012  LR: 0.00000980
Epoch: [1][150/376] Elapsed 1m 57s (remain 2m 55s) Loss: 0.3584(0.3779) Grad: 10505.9062  LR: 0.00000957
Epoch: [1][200/376] Elapsed 2m 36s (remain 2m 16s) Loss: 0.3323(0.3679) Grad: 9094.7666  LR: 0.00000924
Epoch: [1][250/376] Elapsed 3m 15s (remain 1m 37s) Loss: 0.3909(0.3653) Grad: 15641.3428  LR: 0.00000883
Epoch: [1][300/376] Elapsed 3m 53s (remain 0m 58s) Loss: 0.3860(0.3623) Grad: 10783.0293  LR: 0.00000835
Epoch: [1][350/376] Elapsed 4m 32s (remain 0m 19s) Loss: 0.3672(0.3598) Grad: 11859.6064  LR: 0.00000780
Epoch: [1][375/376] Elapsed 4m 51s (remain 0m 0s) Loss: 0.4001(0.3588) Grad: 10182.9209  LR: 0.00000750

  0%|          | 0/130 [00:00<?, ?it/s]

Epoch 1 - avg_train_loss: 0.3588  time: 310s
Epoch 1 - Score: 0.7112
Epoch 1 - Save Best Score: 0.7112 Model

Epoch: [2][0/376] Elapsed 0m 1s (remain 10m 56s) Loss: 0.3539(0.3539) Grad: nan  LR: 0.00000749

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

Epoch: [2][50/376] Elapsed 0m 40s (remain 4m 18s) Loss: 0.3062(0.3261) Grad: 12942.0059  LR: 0.00000687
Epoch: [2][100/376] Elapsed 1m 19s (remain 3m 35s) Loss: 0.3211(0.3279) Grad: 13135.1689  LR: 0.00000621
Epoch: [2][150/376] Elapsed 1m 57s (remain 2m 55s) Loss: 0.3537(0.3248) Grad: 15266.3857  LR: 0.00000552
Epoch: [2][200/376] Elapsed 2m 36s (remain 2m 16s) Loss: 0.2642(0.3224) Grad: 11357.8994  LR: 0.00000483
Epoch: [2][250/376] Elapsed 3m 15s (remain 1m 37s) Loss: 0.3376(0.3226) Grad: 14482.5088  LR: 0.00000413
Epoch: [2][300/376] Elapsed 3m 53s (remain 0m 58s) Loss: 0.2752(0.3222) Grad: 16944.7734  LR: 0.00000346
Epoch: [2][350/376] Elapsed 4m 32s (remain 0m 19s) Loss: 0.3763(0.3236) Grad: 13617.4414  LR: 0.00000282
Epoch: [2][375/376] Elapsed 4m 51s (remain 0m 0s) Loss: 0.3808(0.3236) Grad: 11265.8682  LR: 0.00000251

  0%|          | 0/130 [00:00<?, ?it/s]

Epoch 2 - avg_train_loss: 0.3236  time: 310s
Epoch 2 - Score: 0.7145
Epoch 2 - Save Best Score: 0.7145 Model

Epoch: [3][0/376] Elapsed 0m 1s (remain 9m 51s) Loss: 0.3655(0.3655) Grad: nan  LR: 0.00000250
Epoch: [3][50/376] Elapsed 0m 40s (remain 4m 16s) Loss: 0.2920(0.3021) Grad: 12901.7734  LR: 0.00000192
Epoch: [3][100/376] Elapsed 1m 18s (remain 3m 34s) Loss: 0.2547(0.3029) Grad: 13739.3564  LR: 0.00000140
Epoch: [3][150/376] Elapsed 1m 57s (remain 2m 55s) Loss: 0.2919(0.3035) Grad: 13929.3086  LR: 0.00000096
Epoch: [3][200/376] Elapsed 2m 36s (remain 2m 15s) Loss: 0.2994(0.3045) Grad: 12601.1914  LR: 0.00000059
Epoch: [3][250/376] Elapsed 3m 14s (remain 1m 36s) Loss: 0.4026(0.3060) Grad: 15273.9521  LR: 0.00000030
Epoch: [3][300/376] Elapsed 3m 53s (remain 0m 58s) Loss: 0.3249(0.3070) Grad: 13920.3096  LR: 0.00000011
Epoch: [3][350/376] Elapsed 4m 31s (remain 0m 19s) Loss: 0.3401(0.3073) Grad: 12774.7354  LR: 0.00000001
Epoch: [3][375/376] Elapsed 4m 51s (remain 0m 0s) Loss: 0.2762(0.3078) Grad: 12328.5420  LR: 0.00000000

  0%|          | 0/130 [00:00<?, ?it/s]

Epoch 3 - avg_train_loss: 0.3078  time: 309s
Epoch 3 - Score: 0.7150
Epoch 3 - Save Best Score: 0.7150 Model
========== fold: 1 result ==========
Score: 0.7150
========== fold: 2 training ==========
Some weights of the model checkpoint at studio-ousia/luke-base were not used when initializing LukeModel: ['embeddings.position_ids']
- This IS expected if you are initializing LukeModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LukeModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Epoch: [1][0/376] Elapsed 0m 2s (remain 12m 49s) Loss: 0.4991(0.4991) Grad: nan  LR: 0.00001000
Epoch: [1][50/376] Elapsed 0m 40s (remain 4m 18s) Loss: 0.3288(0.4087) Grad: 14409.6426  LR: 0.00000995
Epoch: [1][100/376] Elapsed 1m 19s (remain 3m 35s) Loss: 0.3803(0.3837) Grad: 12436.3789  LR: 0.00000980
Epoch: [1][150/376] Elapsed 1m 57s (remain 2m 55s) Loss: 0.3580(0.3751) Grad: 11971.0176  LR: 0.00000957
Epoch: [1][200/376] Elapsed 2m 36s (remain 2m 16s) Loss: 0.3944(0.3672) Grad: 10200.6162  LR: 0.00000924
Epoch: [1][250/376] Elapsed 3m 15s (remain 1m 37s) Loss: 0.3626(0.3615) Grad: 10767.9834  LR: 0.00000883
Epoch: [1][300/376] Elapsed 3m 53s (remain 0m 58s) Loss: 0.3824(0.3586) Grad: 13851.0820  LR: 0.00000835
Epoch: [1][350/376] Elapsed 4m 32s (remain 0m 19s) Loss: 0.2977(0.3562) Grad: 10847.4414  LR: 0.00000780
Epoch: [1][375/376] Elapsed 4m 51s (remain 0m 0s) Loss: 0.3593(0.3556) Grad: 10396.1396  LR: 0.00000750

  0%|          | 0/131 [00:00<?, ?it/s]

Epoch 1 - avg_train_loss: 0.3556  time: 310s
Epoch 1 - Score: 0.6926
Epoch 1 - Save Best Score: 0.6926 Model

Epoch: [2][0/376] Elapsed 0m 1s (remain 10m 50s) Loss: 0.2951(0.2951) Grad: nan  LR: 0.00000749

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

Epoch: [2][50/376] Elapsed 0m 40s (remain 4m 17s) Loss: 0.2740(0.3226) Grad: 10570.9238  LR: 0.00000687
Epoch: [2][100/376] Elapsed 1m 19s (remain 3m 35s) Loss: 0.2556(0.3223) Grad: 10600.7109  LR: 0.00000621
Epoch: [2][150/376] Elapsed 1m 57s (remain 2m 55s) Loss: 0.3157(0.3215) Grad: 11448.9209  LR: 0.00000552
Epoch: [2][200/376] Elapsed 2m 36s (remain 2m 16s) Loss: 0.3337(0.3207) Grad: 11960.6152  LR: 0.00000483
Epoch: [2][250/376] Elapsed 3m 14s (remain 1m 37s) Loss: 0.3210(0.3190) Grad: 12569.1182  LR: 0.00000413
Epoch: [2][300/376] Elapsed 3m 53s (remain 0m 58s) Loss: 0.3113(0.3192) Grad: 15602.7305  LR: 0.00000346
Epoch: [2][350/376] Elapsed 4m 32s (remain 0m 19s) Loss: 0.3451(0.3194) Grad: 12479.1758  LR: 0.00000282
Epoch: [2][375/376] Elapsed 4m 51s (remain 0m 0s) Loss: 0.2550(0.3192) Grad: 14304.1045  LR: 0.00000251

  0%|          | 0/131 [00:00<?, ?it/s]

Epoch 2 - avg_train_loss: 0.3192  time: 309s
Epoch 2 - Score: 0.6964
Epoch 2 - Save Best Score: 0.6964 Model

Epoch: [3][0/376] Elapsed 0m 1s (remain 10m 56s) Loss: 0.2960(0.2960) Grad: nan  LR: 0.00000250
Epoch: [3][50/376] Elapsed 0m 40s (remain 4m 18s) Loss: 0.3297(0.2993) Grad: 13540.5801  LR: 0.00000192
Epoch: [3][100/376] Elapsed 1m 19s (remain 3m 35s) Loss: 0.3255(0.3033) Grad: 12514.6338  LR: 0.00000140
Epoch: [3][150/376] Elapsed 1m 57s (remain 2m 55s) Loss: 0.2265(0.3013) Grad: 11094.3223  LR: 0.00000096
Epoch: [3][200/376] Elapsed 2m 36s (remain 2m 16s) Loss: 0.2859(0.3008) Grad: 14315.6689  LR: 0.00000059
Epoch: [3][250/376] Elapsed 3m 15s (remain 1m 37s) Loss: 0.3008(0.3030) Grad: 13897.3779  LR: 0.00000030
Epoch: [3][300/376] Elapsed 3m 53s (remain 0m 58s) Loss: 0.2417(0.3040) Grad: 10566.4502  LR: 0.00000011
Epoch: [3][350/376] Elapsed 4m 32s (remain 0m 19s) Loss: 0.2157(0.3039) Grad: 12941.2520  LR: 0.00000001
Epoch: [3][375/376] Elapsed 4m 51s (remain 0m 0s) Loss: 0.2906(0.3030) Grad: 12920.6104  LR: 0.00000000

  0%|          | 0/131 [00:00<?, ?it/s]

Epoch 3 - avg_train_loss: 0.3030  time: 310s
Epoch 3 - Score: 0.6973
Epoch 3 - Save Best Score: 0.6973 Model
========== fold: 2 result ==========
Score: 0.6973
========== fold: 3 training ==========
Some weights of the model checkpoint at studio-ousia/luke-base were not used when initializing LukeModel: ['embeddings.position_ids']
- This IS expected if you are initializing LukeModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LukeModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Epoch: [1][0/376] Elapsed 0m 1s (remain 10m 59s) Loss: 0.4958(0.4958) Grad: nan  LR: 0.00001000
Epoch: [1][50/376] Elapsed 0m 40s (remain 4m 17s) Loss: 0.3452(0.4044) Grad: 12363.6416  LR: 0.00000995
Epoch: [1][100/376] Elapsed 1m 19s (remain 3m 35s) Loss: 0.3660(0.3786) Grad: 19925.0098  LR: 0.00000980
Epoch: [1][150/376] Elapsed 1m 57s (remain 2m 55s) Loss: 0.3171(0.3704) Grad: 16140.7041  LR: 0.00000957
Epoch: [1][200/376] Elapsed 2m 36s (remain 2m 16s) Loss: 0.4159(0.3657) Grad: 17257.6855  LR: 0.00000924
Epoch: [1][250/376] Elapsed 3m 15s (remain 1m 37s) Loss: 0.3394(0.3612) Grad: 11075.8799  LR: 0.00000883
Epoch: [1][300/376] Elapsed 3m 53s (remain 0m 58s) Loss: 0.3274(0.3591) Grad: 10524.6992  LR: 0.00000835
Epoch: [1][350/376] Elapsed 4m 32s (remain 0m 19s) Loss: 0.3360(0.3560) Grad: 11378.3604  LR: 0.00000780
Epoch: [1][375/376] Elapsed 4m 51s (remain 0m 0s) Loss: 0.3969(0.3559) Grad: 11175.2510  LR: 0.00000750

  0%|          | 0/129 [00:00<?, ?it/s]

Epoch 1 - avg_train_loss: 0.3559  time: 310s
Epoch 1 - Score: 0.7092
Epoch 1 - Save Best Score: 0.7092 Model

Epoch: [2][0/376] Elapsed 0m 1s (remain 9m 57s) Loss: 0.3663(0.3663) Grad: nan  LR: 0.00000749

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

Epoch: [2][50/376] Elapsed 0m 40s (remain 4m 17s) Loss: 0.3728(0.3294) Grad: 11934.7783  LR: 0.00000687
Epoch: [2][100/376] Elapsed 1m 19s (remain 3m 35s) Loss: 0.3214(0.3220) Grad: 14978.9551  LR: 0.00000621
Epoch: [2][150/376] Elapsed 1m 57s (remain 2m 55s) Loss: 0.3135(0.3262) Grad: 11986.5312  LR: 0.00000552
Epoch: [2][200/376] Elapsed 2m 36s (remain 2m 16s) Loss: 0.3313(0.3271) Grad: 12207.2695  LR: 0.00000483
Epoch: [2][250/376] Elapsed 3m 15s (remain 1m 37s) Loss: 0.3188(0.3250) Grad: 12026.5986  LR: 0.00000413
Epoch: [2][300/376] Elapsed 3m 53s (remain 0m 58s) Loss: 0.2981(0.3231) Grad: 13167.3340  LR: 0.00000346
Epoch: [2][350/376] Elapsed 4m 32s (remain 0m 19s) Loss: 0.3348(0.3221) Grad: 14319.9287  LR: 0.00000282
Epoch: [2][375/376] Elapsed 4m 52s (remain 0m 0s) Loss: 0.3216(0.3222) Grad: 11654.2178  LR: 0.00000251

  0%|          | 0/129 [00:00<?, ?it/s]

Epoch 2 - avg_train_loss: 0.3222  time: 310s
Epoch 2 - Score: 0.7127
Epoch 2 - Save Best Score: 0.7127 Model

Epoch: [3][0/376] Elapsed 0m 1s (remain 11m 28s) Loss: 0.3178(0.3178) Grad: nan  LR: 0.00000250
Epoch: [3][50/376] Elapsed 0m 40s (remain 4m 18s) Loss: 0.2559(0.3031) Grad: 12309.8291  LR: 0.00000192
Epoch: [3][100/376] Elapsed 1m 19s (remain 3m 36s) Loss: 0.3148(0.3064) Grad: 11477.2197  LR: 0.00000140
Epoch: [3][150/376] Elapsed 1m 58s (remain 2m 55s) Loss: 0.2656(0.3085) Grad: 14430.7812  LR: 0.00000096
Epoch: [3][200/376] Elapsed 2m 36s (remain 2m 16s) Loss: 0.3364(0.3058) Grad: 13843.5176  LR: 0.00000059
Epoch: [3][250/376] Elapsed 3m 15s (remain 1m 37s) Loss: 0.3061(0.3055) Grad: 13364.3428  LR: 0.00000030
Epoch: [3][300/376] Elapsed 3m 54s (remain 0m 58s) Loss: 0.2687(0.3071) Grad: 14432.4365  LR: 0.00000011
Epoch: [3][350/376] Elapsed 4m 32s (remain 0m 19s) Loss: 0.3941(0.3066) Grad: 15380.2354  LR: 0.00000001
Epoch: [3][375/376] Elapsed 4m 52s (remain 0m 0s) Loss: 0.3350(0.3051) Grad: 11880.7988  LR: 0.00000000

  0%|          | 0/129 [00:00<?, ?it/s]

Epoch 3 - avg_train_loss: 0.3051  time: 310s
Epoch 3 - Score: 0.7120
========== fold: 3 result ==========
Score: 0.7127
========== fold: 4 training ==========
Some weights of the model checkpoint at studio-ousia/luke-base were not used when initializing LukeModel: ['embeddings.position_ids']
- This IS expected if you are initializing LukeModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LukeModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Epoch: [1][0/376] Elapsed 0m 1s (remain 10m 13s) Loss: 0.4930(0.4930) Grad: nan  LR: 0.00001000
Epoch: [1][50/376] Elapsed 0m 40s (remain 4m 17s) Loss: 0.3625(0.4019) Grad: 9871.0430  LR: 0.00000995
Epoch: [1][100/376] Elapsed 1m 19s (remain 3m 35s) Loss: 0.3320(0.3723) Grad: 11552.7803  LR: 0.00000980
Epoch: [1][150/376] Elapsed 1m 57s (remain 2m 55s) Loss: 0.2910(0.3667) Grad: 11206.3662  LR: 0.00000957
Epoch: [1][200/376] Elapsed 2m 36s (remain 2m 16s) Loss: 0.3229(0.3639) Grad: 9929.0117  LR: 0.00000924
Epoch: [1][250/376] Elapsed 3m 15s (remain 1m 37s) Loss: 0.3599(0.3605) Grad: 12253.5986  LR: 0.00000883
Epoch: [1][300/376] Elapsed 3m 53s (remain 0m 58s) Loss: 0.3778(0.3572) Grad: 10848.0781  LR: 0.00000835
Epoch: [1][350/376] Elapsed 4m 32s (remain 0m 19s) Loss: 0.3587(0.3550) Grad: 11650.8945  LR: 0.00000780
Epoch: [1][375/376] Elapsed 4m 51s (remain 0m 0s) Loss: 0.3509(0.3534) Grad: 11111.7480  LR: 0.00000750

  0%|          | 0/131 [00:00<?, ?it/s]

Epoch 1 - avg_train_loss: 0.3534  time: 310s
Epoch 1 - Score: 0.6956
Epoch 1 - Save Best Score: 0.6956 Model

Epoch: [2][0/376] Elapsed 0m 1s (remain 10m 52s) Loss: 0.3592(0.3592) Grad: nan  LR: 0.00000749

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

Epoch: [2][50/376] Elapsed 0m 40s (remain 4m 17s) Loss: 0.2832(0.3241) Grad: 10847.4082  LR: 0.00000687
Epoch: [2][100/376] Elapsed 1m 19s (remain 3m 35s) Loss: 0.2547(0.3176) Grad: 13568.0547  LR: 0.00000621
Epoch: [2][150/376] Elapsed 1m 57s (remain 2m 55s) Loss: 0.2733(0.3155) Grad: 10637.1895  LR: 0.00000552
Epoch: [2][200/376] Elapsed 2m 36s (remain 2m 16s) Loss: 0.2332(0.3154) Grad: 12131.6787  LR: 0.00000483
Epoch: [2][250/376] Elapsed 3m 15s (remain 1m 37s) Loss: 0.2482(0.3173) Grad: 11001.3262  LR: 0.00000413
Epoch: [2][300/376] Elapsed 3m 53s (remain 0m 58s) Loss: 0.3486(0.3186) Grad: 12634.1270  LR: 0.00000346
Epoch: [2][350/376] Elapsed 4m 32s (remain 0m 19s) Loss: 0.3324(0.3189) Grad: 13519.9307  LR: 0.00000282
Epoch: [2][375/376] Elapsed 4m 51s (remain 0m 0s) Loss: 0.2692(0.3187) Grad: 11892.9521  LR: 0.00000251

  0%|          | 0/131 [00:00<?, ?it/s]

Epoch 2 - avg_train_loss: 0.3187  time: 310s
Epoch 2 - Score: 0.7007
Epoch 2 - Save Best Score: 0.7007 Model
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionErrorException ignored in: : <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>can only test a child process
Exception ignored in:
<function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    Traceback (most recent call last):
self._shutdown_workers()  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__

      File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f57a02c9560>self._shutdown_workers()
    if w.is_alive():
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers

    Traceback (most recent call last):
if w.is_alive():  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive

          File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
assert self._parent_pid == os.getpid(), 'can only test a child process'
    self._shutdown_workers()AssertionErrorassert self._parent_pid == os.getpid(), 'can only test a child process':

can only test a child process  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
AssertionError
    : can only test a child processif w.is_alive():

  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

Epoch: [3][0/376] Elapsed 0m 2s (remain 13m 0s) Loss: 0.3305(0.3305) Grad: nan  LR: 0.00000250
Epoch: [3][50/376] Elapsed 0m 40s (remain 4m 19s) Loss: 0.2256(0.2998) Grad: 11824.3564  LR: 0.00000192
Epoch: [3][100/376] Elapsed 1m 19s (remain 3m 36s) Loss: 0.2773(0.2982) Grad: 13149.3184  LR: 0.00000140
Epoch: [3][150/376] Elapsed 1m 58s (remain 2m 56s) Loss: 0.2366(0.3001) Grad: 15074.8301  LR: 0.00000096
Epoch: [3][200/376] Elapsed 2m 36s (remain 2m 16s) Loss: 0.3116(0.2995) Grad: 13132.2383  LR: 0.00000059
Epoch: [3][250/376] Elapsed 3m 15s (remain 1m 37s) Loss: 0.2426(0.2984) Grad: 12908.1123  LR: 0.00000030
Epoch: [3][300/376] Elapsed 3m 54s (remain 0m 58s) Loss: 0.3272(0.3017) Grad: 14389.6611  LR: 0.00000011
Epoch: [3][350/376] Elapsed 4m 33s (remain 0m 19s) Loss: 0.3148(0.3023) Grad: 41373.8477  LR: 0.00000001
Epoch: [3][375/376] Elapsed 4m 52s (remain 0m 0s) Loss: 0.3271(0.3011) Grad: 12769.6211  LR: 0.00000000

  0%|          | 0/131 [00:00<?, ?it/s]

Epoch 3 - avg_train_loss: 0.3011  time: 310s
Epoch 3 - Score: 0.7010
Epoch 3 - Save Best Score: 0.7010 Model
========== fold: 4 result ==========
Score: 0.7010
========== CV ==========
Score: 0.7058

VBox(children=(Label(value=' 0.00MB of 0.00MB uploaded (0.00MB deduped)\r'), FloatProgress(value=1.0, max=1.0)…